### ISSUE TITLE
Documentação do Projeto

### ISSUE THREAD

**Issue by CarlosAndreCordeiro** [ifpe-cti/vaidbike#1]
@fabriciofx Boa tarde Professor, estamos com dúvidas quanto a documentação do projeto, segue o modelo que elaboramos com base no modelo exemplificado pelo senhor.

# VaidBike

O projeto de Aplicação escolhido tem como objetivo intermediar a interação entre os usuários facilitando o aluguel de bicicletas entre locador e locatário.

## Motivação

A ociosidade pode ser um prejuízo em muitos aspectos, e se você pudesse pegar aquela bike que você não usa mais e ganhar uma grana extra?
Talvez você queria começar a pedalar, mas não quer gastar uma "fortuna" com uma Bike e acessórios para só depois descobrir se vai se identificar com o ciclismo.

## Soluções existentes

Bike Itau, Bike santos, ambos utilizam plataformas que possuem suas próprias bicicletas, esses serviços estão disponíveis apenas em capitais.

## Inovação

O grande diferencial do VaidBike é que você ou qualquer pessoa pode ganhar uma grana extra alugando a sua bike que fica geralmente jogada na garagem, ou se você pretende sair do sedentarismo e não sabe por onde começar, aqui está uma ótima possibilidade de melhorar sua qualidade de vida alugando a bike de seu vizinho.

## Público alvo

Qualquer pessoa que deseja mudar a rotina ou começar a praticar ciclismo, melhorar a qualidade de vida, ou simplesmente evitar o trânsito.

## Monetização

A monetização virá através de "comissões" pelos aluguéis das bicicletas, e pela intermediação do serviço.

## Ferramental utilizado

As ferramentas utilizadas na construção do Projeto serão:
- NetBeans; 
- Android Studio;  
- PostgreSQL;
- Maven;
- Gradle.
- 
As linguagens de programação escolhidas foram:
- Java;
- CSS;
- JSF;
- HTML.

## Contribuidores

- [@vsnepomuceno](https://github.com/vsnepomuceno) como Vilmar Nepomuceno
- [@milenamaced](https://github.com/milenamaced) como Milena Macedo 
- [@Lucianocljr](https://github.com/Lucianocljr)  como Luciano Júnior
- [@CarlosAndreCordeiro](https://github.com/CarlosAndreCordeiro) como Carlos Cordeiro
- [@Adriellycl](htts://githy.com/Adriellycl) como Adrielly Sales

**Comment by fabriciofx** [comment]
@CarlosAndreCordeiro Uma issue é apenas para você *dizer* o que vai fazer e uma discussão sobre o que será feito. O produto (código, documentação, figuras) deve ser submetido via PRs.
