### ISSUE TITLE
Interface Usuario 

### ISSUE THREAD

**Issue by CarlosAndreCordeiro** [ifpe-cti/vaidbike#10]
Vou implementar a interface usuarioDao.  @MilenaMaced

**Comment by MilenaMaced** [comment]
Você deve criar os métodos específicos da interface do usuário.

**Comment by MilenaMaced** [comment]
@CarlosAndreCordeiro  Vou fazer está interface, para testar as configurações que foram feitas nos repositório, para que e possa fazer os PRs também.
