### ISSUE TITLE
Interface Locacao 

### ISSUE THREAD

**Issue by MilenaMaced** [ifpe-cti/vaidbike#15]
Criar os métodos específicos da Locação se necessários.

**Comment by Lucianocljr** [comment]
@MilenaMaced quanto ao termo "Interface" empregada nesta issue, estás se referindo ao CRUD?

**Comment by MilenaMaced** [comment]
@Lucianocljr a interface CRUD ela já está pronta, a que estou me referindo  e a que implementa ela que é a especifica daquela classe, exemplificando você tem uma classe cliente e estoque, o CRUD vai conter as informações inserir, deletar , alterar e recuperar, só que na classe estoque você precisa recuperar produtos pelo código de barra , mas não tem no CRUD porque as outras classes não necessitam deste método, então por isso que você necessita de uma interface para essa classe, pois ela vai conter este método especifico.  Com isso você cria outra interface relacionada a classe locacao extends a interface DAO.

**Comment by MilenaMaced** [comment]
@Lucianocljr 
Você acha que precisa de métodos nesta interface?
 Se não deixa ela fazia só estendendo  o DAO.

**Comment by Lucianocljr** [comment]
@MilenaMaced Podemos fazer justamente o que você retratou na resposta anterior, podemos criar a interface especifica vazia, e a medida que vamos identificando os requisitos adicionais do sistema podemos utilizar. Ok? Vou cria-la!
