### ISSUE TITLE
Classe Locacao - Hibernate

### ISSUE THREAD

**Issue by MilenaMaced** [ifpe-cti/vaidbike#16]
Ela deve conter a classe de conexão com Banco de Dados e deve fazer mapeamento desta classe no arquivo de Configuração.
OBS: Usar o tratamento de exerções com mensagens que façam sentido.

**Comment by Lucianocljr** [comment]
@MilenaMaced Qual atributo da classe localização uso para fazer os serviços de busca?

**Comment by MilenaMaced** [comment]
@Lucianocljr  pode me explicar com mais detalhes?

**Comment by Lucianocljr** [comment]
@MilenaMaced posso sim. Exemplo: Se eu for buscar uma pessoal no banco de dados, qual o atributo que vou usar para realizar a comparação de busca? Pelo nome, pelo RG, CPF, enfim ...
No caso da locação, qual o método que vou utilizar para achar aquela locação?

**Comment by Lucianocljr** [comment]
@MilenaMaced vi aqui na classe básica, vai ser o código da locação.

**Comment by Lucianocljr** [comment]
@MilenaMaced o atributo "codigo" será auto incrementado? Se for já posso fazer a anotação do atributo?

**Comment by MilenaMaced** [comment]
@Lucianocljr pode usar código ou cpf.
Por que os dois são únicos.
ACHO MELHOR CPF E VOCÊ?

**Comment by MilenaMaced** [comment]
MAIS VOCÊ TEM O USUARIO é o usuário é um atributo de locação, você pode recuperar cpf a partir disso.
@Lucianocljr
