### ISSUE TITLE
Escolha da Licença

### ISSUE THREAD

**Issue by CarlosAndreCordeiro** [ifpe-cti/vaidbike#2]
@fabriciofx boa tarde Professor, estamos em dúvida quanto a escolha da licença. Conforme questionado em sala de aula, conversamos entre nós escolhemos licença de código aberto. Visto isso , com implementar isso no projeto?

**Comment by viniciussoaresti** [comment]
@CarlosAndreCordeiro recomendo a do MIT também, estou utilizando-a.

**Comment by CarlosAndreCordeiro** [comment]
Otimo, Vamos fechar a issue
