### ISSUE TITLE
Erro da criação do projeto

### ISSUE THREAD

**Issue by CarlosAndreCordeiro** [ifpe-cti/vaidbike#3]
@fabriciofx Fabrício, Milena está como colaboradora/ administradora do projeto?
Por gentileza verificar se o repositório do git está configurado como Milena a administradora do projeto.

**Comment by fabriciofx** [comment]
@CarlosAndreCordeiro O problema é que ela não tinha aceitado o convite. Verifiquei e agora ela aceitou. @MilenaMaced Tudo certo do seu lado? @CarlosAndreCordeiro Caso esteja, favor fechar a issue.

**Comment by CarlosAndreCordeiro** [comment]
#close
