### ISSUE TITLE
Atualização do nome do Projeto

### ISSUE THREAD

**Issue by CarlosAndreCordeiro** [ifpe-cti/vaidbike#4]
@fabriciofx, @vsnepomuceno , Boa tarde, conforme visto na issue #1, o nome do projeto assim como sua funcionalidade mudou. Sendo assim precisamos mudar/criar o repositório com o devido nome "VaidBike".

**Comment by fabriciofx** [comment]
@CarlosAndreCordeiro ok, vou renomear.

**Comment by fabriciofx** [comment]
@CarlosAndreCordeiro @MilenaMaced @adriellycl @Lucianocljr @vsnepomuceno Projeto renomeado. @CarlosAndreCordeiro Se você concorda com a mudança, favor fechar a issue.
