### ISSUE TITLE
Correção de  anotações para Persistência de Dados. 

### ISSUE THREAD

**Issue by CarlosAndreCordeiro** [ifpe-cti/vaidbike#44]
@MilenaMaced, @Lucianocljr, @adriellycl,  Para conseguir realizar um teste de persistência de dados, foi necessário alterar as outras classes, ainda assim, é necessário que cada um confira suas classes e seus devidos mapeamentos. 
O objetivo dessa Issue é testar a persistência de dados e verificar se foram criadas as devidas tabelas no PgAdmin. 
Cada um deve realizar um teste de persistência de dados com a classe na qual está responsável e verificar individualmente antes de um teste da mesma forma com todas as classes.
Sem mais para o momento, Carlos André.

**Comment by MilenaMaced** [comment]
@CarlosAndreCordeiro  Alguns mapeamentos estão  errados, vou corrigir.
