### ISSUE TITLE
Criação do Repositório

### ISSUE THREAD

**Issue by MilenaMaced** [ifpe-cti/vaidbike#5]
@fabriciofx @vsnepomuceno   Não tenho acesso para enviar o projeto para o repositório.
Como faço isso? ou Tem alguma coisa errada?
![captura de tela 2018-03-30 19 11 11](https://user-images.githubusercontent.com/36709416/38155570-d87a138c-344e-11e8-9344-c0205c2431c9.png)

**Comment by fabriciofx** [comment]
@MilenaMaced Você @carloscordeiro e @Lucianocljr receberam o convite mas ainda não aceitaram. Precisam aceitar o convite!

**Comment by CarlosAndreCordeiro** [comment]
@fabriciofx, Não encontrei o convite no e-mail, tem outro lugar que eu possa encontrar aqui mesmo no Git?

**Comment by fabriciofx** [comment]
@CarlosAndreCordeiro O convite foi para outro login. Vou reenviar.

**Comment by MilenaMaced** [comment]
@fabriciofx Achei convite agora está  
OK....

**Comment by fabriciofx** [comment]
@MilenaMaced Se está tudo ok, favor fechar a issue.

**Comment by CarlosAndreCordeiro** [comment]
Agora sim.
