### ISSUE TITLE
Divisão de Tarefas

### ISSUE THREAD

**Issue by MilenaMaced** [ifpe-cti/vaidbike#6]
Como vamos dividir as partes do projeto? 
@CarlosAndreCordeiro @Lucianocljr @adriellycl @vsnepomuceno

**Comment by fabriciofx** [comment]
@MilenaMaced Você é a arquiteta. Você é quem decide isso. Abra as issues e vá alocando...

**Comment by MilenaMaced** [comment]
Eu ficarei responsável pelas classes e interfaces.
@CarlosAndreCordeiro , Ficará responsável pelo banco de dados.
@Lucianocljr , Ficará responsável pela Validações de dados no Model.
@adriellycl , Ficará responsável pelos Controladores do projeto. 
Divisão baseada na arquitetura de software MVC.

**Comment by CarlosAndreCordeiro** [comment]
Ok

**Comment by Lucianocljr** [comment]
@MilenaMaced Ok, entendido!

**Comment by MilenaMaced** [comment]
@CarlosAndreCordeiro , @Lucianocljr , @adriellycl.
Teve alterações na forma de divisão das Tarefas do projeto, pois estava ocorrendo ociosidade dos integrantes do grupo e objetivo do projeto que todos os integrantes possa trabalha com todas partes do projeto não era o que estava ocorrendo, pois a divisão estava sendo por partes de forma Vertical e não todos fazendo todas as partes do projeto que é o objetivo.

**Comment by MilenaMaced** [comment]
Novas divisões: 
As classes devem está com todas as partes do MVC menos a View. 
@Lucianocljr estar responsável  pela classe Locacao
@adriellycl  estar responsável pela classe Pagamento
@CarlosAndreCordeiro Está responsável pela classe Usuario
Eu com os testes

**Comment by Lucianocljr** [comment]
@MilenaMaced Ok, entendido!
