### ISSUE TITLE
Diagrama de Classe

### ISSUE THREAD

**Issue by MilenaMaced** [ifpe-cti/vaidbike#9]
@CarlosAndreCordeiro , corrige o diagrama de classe.

*O que precisa ser feito PARA MELHORAR :

1) Mudar nome da classe locador para cliente 

Classe Bike:

deve-se colocar atributo de tipo de bicleta(trilha, corrida, passeio)

Classe Locacao:

2) Verificar diagrama de classe está mal feito(dados desnecessários na classe locacao)
3) Dentro da classe locacao deve ter o tipo de pagamento para o cliente(que pode ser uma classe)
4) Valor pago por diária ou por horas que está com a bicicleta(para formulação de metódos)

**Comment by CarlosAndreCordeiro** [comment]
Corrigido. Fechando issue.
