### ISSUE TITLE
Mudança na Licença

### ISSUE THREAD

**Issue by CarlosAndreCordeiro** [ifpe-cti/vaidbike#97]
@MilenaMaced  Devido À mudanças na equipe devemos modificar a licença, retirando o nome de @Lucianocljr  e colocando o nome de @lucasmendsc ?

**Comment by fabriciofx** [comment]
@CarlosAndreCordeiro Depende. Há código desenvolvido pelo @Lucianocljr? Se houver, deve ser mantido o nome dele...

**Comment by MilenaMaced** [comment]
@CarlosAndreCordeiro,  Pode fazer a mudança, ele não chegou a submeter nenhum código para o repositório.

**Comment by CarlosAndreCordeiro** [comment]
@MilenaMaced Assim que o fizer submeto e fecho a issue.

**Comment by MilenaMaced** [comment]
Vou Fazer está mudança. @CarlosAndreCordeiro
